stages:
  - docker_image
  - deploy

variables:
  DOCKER_BUILDKIT: 1

  DOCKER_IMAGE_VERSION: docker:27.2.0


.docker-build-base:
  stage: docker_image
  image: $DOCKER_IMAGE_VERSION
  tags:
    - forsim
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        TAG_SUFFIX=""
        LATEST_TAG="latest"
        BUILD_PROFILE="production"
      else
        TAG_SUFFIX="-dev"
        LATEST_TAG="dev"
        BUILD_PROFILE="dev"
      fi
      FULL_IMAGE_NAME="$CI_REGISTRY_IMAGE/$IMAGE_NAME"
      COMMIT_TAG="${CI_COMMIT_SHORT_SHA}${TAG_SUFFIX}"
      if [ "$IMAGE_NAME" == "backend" ] || [ "$IMAGE_NAME" == "lightrag" ]; then
        PROFILE_BUILD_ARG="--build-arg BUILD_PROFILE=$BUILD_PROFILE"
      else
        PROFILE_BUILD_ARG=""
      fi
    - docker pull "$FULL_IMAGE_NAME:$LATEST_TAG" || true
    - |
      docker build --cache-from "$FULL_IMAGE_NAME:$LATEST_TAG" \
        $PROFILE_BUILD_ARG \
        -t "$FULL_IMAGE_NAME:$COMMIT_TAG" \
        -t "$FULL_IMAGE_NAME:$LATEST_TAG" \
        -f $DOCKERFILE_PATH $BUILD_CONTEXT
    - docker push "$FULL_IMAGE_NAME:$COMMIT_TAG"
    - docker push "$FULL_IMAGE_NAME:$LATEST_TAG"


build_services_backend:
  extends: .docker-build-base
  parallel:
    matrix:
      - IMAGE_NAME: [backend]
  variables:
    DOCKERFILE_PATH: "Dockerfile.server"
    BUILD_CONTEXT: "."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - server/**/*
        - shared
        - server_gateway 
        - pyproject.toml
        - Dockerfile.server
        - config 
        - client_gateway
        - .gitlab-ci.yml

build_services_lightrag:
  extends: .docker-build-base
  parallel:
    matrix:
      - IMAGE_NAME: [lightrag]
  variables:
    DOCKERFILE_PATH: "Dockerfile.lightrag"
    BUILD_CONTEXT: "${IMAGE_NAME}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - lightrag_server/*
        - local_embeddings/*
        - docker-compose.yml
        - config 
        - Dockerfile.lightrag 
        - .gitlab-ci.yml

.deploy_template:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - |
      curl --fail --request POST "$WEBHOOK_URL" --header "Content-Type: application/json" --header "X-Gitlab-Token: $KOMODO_SECRET" --data "{ }"

deploy_komodo_prod:
  extends: .deploy_template
  variables:
    WEBHOOK_URL: $KOMODO_WEBHOOK_URL
    KOMODO_SECRET: $KOMODO_WEBHOOK_SECRET
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
